#!/bin/sh

# shell script to conveniently switch night light mode on/off


nightlight=$(gsettings get org.gnome.settings-daemon.plugins.color night-light-enabled)


if [ $nightlight = true ]
then
  gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled false
  echo ' - Night Light has been disabled'

else
  gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
  echo ' - Night Light has been enabled'

fi
